site-name: Firebolt docs process
site_url: https://example.com
nav:
    - Home: 'index.md'
    - 'Getting started': 'index.md'
    - 'Architecture overview': 'architecture-overview.md'
    - 'Working with engines': '/working-with-engines/README.md'
        - 'Understanding engine fundamentals': '/working-with-engines/understanding-engine-fundamentals.md'
        - 'Working with engines using DDL': ''/working-with-engines/working-with-engines-using-ddl.md'
        - 'Working with engines using the REST API': '/working-with-engines/working-with-engines-using-the-rest-api.md'
        - 'Working with engines using the Firebolt Manager': '/working-with-engines/working-with-engines-using-the-firebolt-manager.md'
        - 'Tuning engine performance': '/working-with-engines/tuning-engine-performance.md'
    - 'Concepts': '/concepts/README.md'
        - 'Working with tables': '/concepts/working-with-tables.md'
        - 'Using indexes': '/concepts/get-instant-query-response-time.md'
        - 'Working with semi-structured data': '/concepts/working with partitions.md'
            -'Working with arrays': '/concepts/working-with-semi-structured-data/README.md'
            -'Ingesting semi-structured data': '/concepts/working-with-semi-structured-data/working-with-arrays.md'
            -'Working with Parquet arrays and maps': '/concepts/working-with-semi-structured-data/ingesting-semi-structured-data.md'
        -'Working with partitions': '/concepts/working-with-semi-structured-data/working-with-parquet-arrays-of-structs-and-maps.'md
    - 'Writing, editing, and running SQL': '/working-with-our-sql-editor/README.md'
    - 'Keyboard shortcuts': '/working-with-our-sql-editor/keyboard-shortcuts-for-sql-workspace.'md
    - 'Loading data': '/loading-data/README.md'
        -'Working with external tables': '/loading-data/loading-data-into-firebolt.md'
        -'Incrementally loading data tutorial': '/loading-data/continuously-loading-data.md'
        -'Using AWS roles to access Amazon S3': '/loading-data/configuring-aws-role-access-amazon-s3.md'
    'Integrations overview': '/integrations/integration-overview.md'
